### ISSUE TITLE
Issue with json in IE

### ISSUE THREAD

**Issue by dskanth** [Fabryz/support-chat#1]
In IE, the user list does not appear in the right side, as in Firefox and chrome. 

When i look at the code in chat.js, i see that this line of code is not executed.. users.append('<li><a class="userNick" href="#".... Probably there is a problem in IE with looping json. (data.users.forEach). 

But surprisingly, in the node console, it shows the total users correctly. 
I also tried using the latest jquery, but no use.

**Comment by Fabryz** [comment]
Closing, because apparently I didn't have time to check in 10 years
